### PR TITLE
Add get_notifications + event support

### PR DESCRIPTION
**Pull request by CloCkWeRX**

### CODE REVIEW

**Review by sriramsv — APPROVED** [review]

**Comment by sriramsv** [comment]
Let me know how this one goes, happy to merge if you can show some working examples

**Comment by CloCkWeRX** [comment]
https://github.com/namaggarwal/splitwise/pull/68 got merged.

**Comment by CloCkWeRX** [comment]
TODO: I need to check this in a bit and see if it should stop using my deps, use the upstream version

**Comment by CloCkWeRX** [comment]
https://github.com/namaggarwal/splitwise/compare/v2.2.0...v2.4.0 - neat, the upstream library has modification events as well as notifications now :)

**Comment by CloCkWeRX** [comment]
@sriramsv - should be mergable

**Pull request merged**
